services:
  megxl:
    build: .
    image: megxl:latest
    working_dir: /app
    shm_size: "32gb"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./data:/app/data
      - /server/path/to/datasets:/datasets:ro
      - /server/path/to/weights:/weights:ro
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
