QUEUE_FILE="$RUN_ROOT/jobs.tsv"
NEXT_FILE="$RUN_ROOT/next_job.txt"
RUNS_FILE="$RUN_ROOT/runs.tsv"
WORKER_ENV_FILE="$RUN_ROOT/worker.env"
LATEST_FILE="results/eeg_language_curriculum_three_models/latest_run.txt"
mkdir -p "$(dirname "$LATEST_FILE")"
printf '%s\n' "$STAMP" > "$LATEST_FILE"
printf 'label\tinitialization\teeg_embedding_id\n' > "$QUEUE_FILE"
printf 'from_scratch\tscratch\t2\n' >> "$QUEUE_FILE"
printf 'megxl_eeg2\tpretrained\t2\n' >> "$QUEUE_FILE"
printf 'megxl_eeg1\tpretrained\t1\n' >> "$QUEUE_FILE"
printf '0\n' > "$NEXT_FILE"
printf 'label\tinitialization\teeg_embedding_id\tgpu\tstatus\treading_checkpoint\tfinal_checkpoint\tmessage\n' > "$RUNS_FILE"
printf 'WANDB_MODE=%s\n' "$WANDB_MODE" > "$WORKER_ENV_FILE"
printf 'EEG_SEED=%s\n' "$SEED" >> "$WORKER_ENV_FILE"
printf 'EEG_CACHE_DIR=%s\n' "$CACHE" >> "$WORKER_ENV_FILE"
printf 'EEG_PIPELINE_RUN_ROOT=%s\n' "$RUN_ROOT" >> "$WORKER_ENV_FILE"
printf 'EEG_TRAIN_LOG_ROOT=%s\n' "$LOG_ROOT" >> "$WORKER_ENV_FILE"
printf 'EEG_CHECKPOINT_ROOT=%s\n' "$CKPT_ROOT" >> "$WORKER_ENV_FILE"
printf 'EEG_READING_BATCH_SIZE=%s\n' "$READ_BATCH" >> "$WORKER_ENV_FILE"
printf 'EEG_LANGUAGE_BATCH_SIZE=%s\n' "$LANG_BATCH" >> "$WORKER_ENV_FILE"
printf 'CRISS_CROSS_CHECKPOINT=%s\n' "$MEGXL" >> "$WORKER_ENV_FILE"
